apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: AllParametersTemplate
  namespace: default
  annotations:
    alauda.io/displayName.zh-CN: "All params temp 中文"
    alauda.io/displayName.en: "All params temp english"
    alauda.io/description.zh-CN: "All params temp 中文描述"
    alauda.io/description.en: "All params temp english description"
    alauda.io/version: "0.1.0"
    alauda.io/style.icon: golang,docker,sonarqube,kubernetes,python,nodejs
  labels:
    category: All
spec:
  engine: graph
  withSCM: true
  agent:
    label: base
  stages:
    - name: All
      tasks:
        - name: AllParametersTask
          kind: PipelineTaskTemplate
          type: AllParametersTask
  arguments:
    - displayName:
        zh-CN: "基本参数"
        en: "Basic paramters"
      items:
        - name: "Boolean"
          binding:
            - AllParametersTask.args.Boolean
          schema:
            type: boolean
          display:
            type: boolean
            name:
              zh-CN: "布尔"
              en: "Boolean"
            description:
              zh-CN: "布尔 描述"
              en: "boolean description"
        - name: "StringWithDefault"
          binding:
            - AllParametersTask.args.StringWithDefault
          schema:
            type: string
          required: false
          default: "has a value"
          display:
            type: string
            name:
              zh-CN: "默认值的字符串"
              en: "String with default"
            description:
              zh-CN: "带默认值的字符串参数"
              en: "String parameter with default value"
        - name: "StringNoDefaultRequired"
          binding:
            - AllParametersTask.args.StringNoDefaultRequired
          schema:
            type: string
          required: true
          display:
            type: string
            advanced: true
            name:
              zh-CN: "必填没有默认值的字符串"
              en: "Compulsory string without default"
            description:
              zh-CN: "必填没有默认值的字符串描述"
              en: "Compulsory string without default description"
        - name: "CodeWithDefault"
          binding:
            - AllParametersTask.args.CodeWithDefault
          schema:
            type: string
          required: false
          default: "has a value"
          display:
            type: code
            name:
              zh-CN: "默认值的代码"
              en: "code with default"
            description:
              zh-CN: "带默认值的代码参数. 如果不填值这个模版会渲染失败"
              en: "Code parameter with default value"
        - name: "CodeNoDefaultRequired"
          binding:
            - AllParametersTask.args.CodeNoDefaultRequired
          schema:
            type: string
          required: true
          display:
            type: code
            advanced: true
            name:
              zh-CN: "必填没有默认值的代码"
              en: "Compulsory code without default"
            description:
              zh-CN: "必填没有默认值的代码描述"
              en: "Compulsory code without default description"
    - displayName:
        zh-CN: "代码仓库"
        en: "Code Repository"
      items:
        - name: "CodeRepoRequired"
          binding:
            - AllParametersTask.args.CodeRepoRequired
          schema:
            type: alauda.io/coderepositorymix
          required: true
          display:
            type: alauda.io/coderepositorymix
            name:
              zh-CN: "代码仓库"
              en: "Code Repository"
            description:
              zh-CN: "选择已为项目分配的代码仓库"
              en: "Select a code repository for the project."
        - name: "CodeRepoBranch"
          binding:
            - AllParametersTask.args.CodeRepoBranch
          schema:
            type: alauda.io/codebranch
          required: true
          display:
            type: alauda.io/codebranch
            name:
              zh-CN: "代码仓库分支"
              en: "Code Repository branch"
            description:
              zh-CN: "选择已为项目分配的代码仓库分支"
              en: "Select a code repository branch"
    - displayName:
        zh-CN: "镜像仓库"
        en: "Image Repository"
      items:
        - name: "ImageRepositoryRequired"
          binding:
            - AllParametersTask.args.ImageRepositoryRequired
          schema:
            type: alauda.io/dockerimagerepositorymix
          required: true
          display:
            type: alauda.io/dockerimagerepositorymix
            name:
              zh-CN: "镜像仓库"
              en: Repository
            description:
              zh-CN: "选择或者输入镜像仓库"
              en: "Image repo description"
        - name: "ImageRepositoryPull"
          binding:
            - AllParametersTask.args.ImageRepositoryPull
          schema:
            type: alauda.io/dockerimagerepositorypullmix
          required: false
          display:
            type: alauda.io/dockerimagerepositorypullmix
            name:
              zh-CN: "pull镜像仓库"
              en: Repository pull
            description:
              zh-CN: "pull 选择或者输入镜像仓库"
              en: "pull Image repo description"
    - displayName:
        zh-CN: "绑定"
        en: "Binding"
      items:
        - name: "CodeQualityBinding"
          binding:
            - AllParametersTask.args.CodeQualityBinding
          schema:
            type: alauda.io/toolbinding
          display:
            type: alauda.io/toolbinding
            args:
              bindingKind: codequalitytool
              bindingToolType: Sonarqube
            name:
              zh-CN: "SonarQube 实例"
              en: "SonarQube instance"
            description:
              zh-CN: "选择要使用的 SonarQube 实例"
              en: "Select a SonarQube binding"
          required: true
    - displayName:
        zh-CN: "集群与应用"
        en: "Cluster App"
      items:
        - name: "Cluster"
          binding:
            - AllParametersTask.args.Cluster
          schema:
            type: alauda.io/clustername
          display:
            type: alauda.io/clustername
            name:
              zh-CN: "集群"
              en: "Cluster"
            description:
              zh-CN: "集群描述"
              en: "Cluster description"
          required: true
        - name: "Namespace"
          binding:
            - AllParametersTask.args.Namespace
          schema:
            type: alauda.io/k8snamespace
          display:
            type: alauda.io/k8snamespace
            name:
              zh-CN: "命名空间"
              en: "Namespace"
            description:
              zh-CN: "命名空间描述"
              en: "Namespace description"
          required: true
        - name: "App"
          binding:
            - AllParametersTask.args.App
          schema:
            type: alauda.io/applicationName
          display:
            type: alauda.io/applicationName
            name:
              zh-CN: "应用"
              en: "App"
            description:
              zh-CN: "应用 描述"
              en: "App description"
          required: true
        - name: "ComponentClass"
          binding:
            - AllParametersTask.args.ComponentClass
          schema:
            type: alauda.io/componentClass
          display:
            type: alauda.io/componentClass
            name:
              zh-CN: "组件类型"
              en: "Component Class"
            description:
              zh-CN: "组件类型 描述"
              en: "Component Class description"
          required: true
        - name: "Component"
          binding:
            - AllParametersTask.args.Component
          schema:
            type: alauda.io/componentName
          display:
            type: alauda.io/componentName
            name:
              zh-CN: "组件"
              en: "Component"
            description:
              zh-CN: "组件 描述"
              en: "Component description"
          required: true
        - name: "Container"
          binding:
            - AllParametersTask.args.Container
          schema:
            type: alauda.io/containerName
          display:
            type: alauda.io/containerName
            name:
              zh-CN: "容器"
              en: "Container"
            description:
              zh-CN: "容器 描述"
              en: "Container description"
          required: true
